version: '3'

services:
  app:
    build: .
    #ports:
    #  - "5000:5000"
    volumes:
      - "./src:/home/pyuser/src"
      - "./data:/home/pyuser/data"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: /bin/bash
